#!/bin/bash

# ============================================
# KJ & Associates CMS - Quick Setup Script
# ============================================
# This script helps you configure a new project
# by updating all necessary configuration files.
# ============================================

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo ""
echo -e "${GREEN}╔═══════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║       KJ & Associates CMS - Quick Setup Script        ║${NC}"
echo -e "${GREEN}╚═══════════════════════════════════════════════════════╝${NC}"
echo ""

# Function to prompt for input with default value
prompt_with_default() {
    local prompt="$1"
    local default="$2"
    local var_name="$3"
    
    if [ -n "$default" ]; then
        read -p "$prompt [$default]: " value
        value="${value:-$default}"
    else
        read -p "$prompt: " value
    fi
    
    eval "$var_name='$value'"
}

# Function to prompt for password (hidden input)
prompt_password() {
    local prompt="$1"
    local var_name="$2"
    
    read -s -p "$prompt: " value
    echo ""
    eval "$var_name='$value'"
}

echo -e "${BLUE}This script will configure your CMS project.${NC}"
echo -e "${BLUE}You'll need your Supabase and API server details.${NC}"
echo ""

# ============================================
# Gather Information
# ============================================

echo -e "${YELLOW}=== Supabase Configuration ===${NC}"
prompt_with_default "Supabase URL (e.g., https://xxx.supabase.co)" "" SUPABASE_URL
prompt_with_default "Supabase Anon Key" "" SUPABASE_ANON_KEY
prompt_with_default "Supabase Service Role Key" "" SUPABASE_SERVICE_ROLE_KEY

echo ""
echo -e "${YELLOW}=== Backend API Configuration ===${NC}"
prompt_with_default "Backend API URL (e.g., http://31.97.79.197:3001/api)" "" API_URL
prompt_with_default "Backend Server Port" "3001" API_PORT

echo ""
echo -e "${YELLOW}=== Frontend Configuration ===${NC}"
prompt_with_default "Frontend URL (e.g., https://example.com/demo)" "" FRONTEND_URL
prompt_with_default "Allowed Origins (comma-separated, e.g., https://example.com)" "$FRONTEND_URL" ALLOWED_ORIGINS

echo ""
echo -e "${YELLOW}=== CMS Admin Configuration ===${NC}"
prompt_with_default "Admin Password" "KJAdmin2024!" ADMIN_PASSWORD

echo ""
echo -e "${YELLOW}=== Site Branding ===${NC}"
prompt_with_default "Company Name" "KJ & Associates" COMPANY_NAME
prompt_with_default "Company Subtitle" "Consultancy Ltd" COMPANY_SUBTITLE

# ============================================
# Update Configuration Files
# ============================================

echo ""
echo -e "${BLUE}Updating configuration files...${NC}"

# 1. Update js/config.js
echo -e "  ${GREEN}✓${NC} Updating js/config.js..."
cat > js/config.js << EOF
/**
 * Frontend Configuration
 * Auto-generated by setup.sh
 */

(function() {
  const metaApiBase = document.querySelector('meta[name="api-base-url"]')?.content;
  const globalApiOverride = window.API_BASE_URL_OVERRIDE;

  const isLocalhost = window.location.hostname === 'localhost' || 
                      window.location.hostname === '127.0.0.1' ||
                      window.location.protocol === 'file:';

  let apiUrl;
  if (globalApiOverride) {
    apiUrl = globalApiOverride;
  } else if (metaApiBase) {
    apiUrl = metaApiBase;
  } else if (isLocalhost) {
    apiUrl = 'http://localhost:3001/api';
  } else {
    // Production API URL
    apiUrl = '${API_URL}';
  }
  
  window.API_BASE_URL = apiUrl;
  window.USE_API = true;
  window.DEBUG = isLocalhost;

  console.log(\`[Config] Environment: \${isLocalhost ? 'Development' : 'Production'}\`);
  console.log(\`[Config] API URL: \${window.API_BASE_URL}\`);
})();
EOF

# 2. Update js/supabase-config.js
echo -e "  ${GREEN}✓${NC} Updating js/supabase-config.js..."
cat > js/supabase-config.js << EOF
/**
 * Supabase Configuration
 * Auto-generated by setup.sh
 */

(function() {
  // Supabase credentials
  window.SUPABASE_URL = '${SUPABASE_URL}';
  window.SUPABASE_ANON_KEY = '${SUPABASE_ANON_KEY}';
  
  console.log('[Supabase] Configuration loaded');
})();
EOF

# 3. Update server/.env
echo -e "  ${GREEN}✓${NC} Creating server/.env..."
cat > server/.env << EOF
# Server Configuration
# Auto-generated by setup.sh

NODE_ENV=production
PORT=${API_PORT}

# Supabase
SUPABASE_URL=${SUPABASE_URL}
SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}

# CORS
ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
FRONTEND_URL=${FRONTEND_URL}
EOF

# 4. Update admin password in admin/index.html
echo -e "  ${GREEN}✓${NC} Updating admin password..."
if [[ "$OSTYPE" == "darwin"* ]]; then
    # macOS
    sed -i '' "s/const ADMIN_PASSWORD = '.*';/const ADMIN_PASSWORD = '${ADMIN_PASSWORD}';/" admin/index.html
else
    # Linux
    sed -i "s/const ADMIN_PASSWORD = '.*';/const ADMIN_PASSWORD = '${ADMIN_PASSWORD}';/" admin/index.html
fi

# ============================================
# Summary
# ============================================

echo ""
echo -e "${GREEN}╔═══════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║              Configuration Complete!                   ║${NC}"
echo -e "${GREEN}╚═══════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "${BLUE}Files updated:${NC}"
echo "  • js/config.js"
echo "  • js/supabase-config.js"
echo "  • server/.env"
echo "  • admin/index.html (password)"
echo ""
echo -e "${YELLOW}Next Steps:${NC}"
echo ""
echo "  1. ${BLUE}Setup Database:${NC}"
echo "     - Open Supabase SQL Editor"
echo "     - Run: database/supabase-schema.sql"
echo ""
echo "  2. ${BLUE}Deploy Backend (Coolify):${NC}"
echo "     - Push to GitHub"
echo "     - Deploy /server folder from Coolify"
echo "     - Or run on server:"
echo "       cd server && npm install && pm2 start src/index.js --name cms-api"
echo ""
echo "  3. ${BLUE}Seed Database (Optional):${NC}"
echo "     cd server && node scripts/seed-from-cms-defaults.js"
echo ""
echo "  4. ${BLUE}Deploy Frontend (20i):${NC}"
echo "     - Upload all files (except /server) to 20i"
echo "     - Or deploy from GitHub"
echo ""
echo -e "${GREEN}Your CMS admin will be at: ${FRONTEND_URL}/admin/${NC}"
echo -e "${GREEN}Password: ${ADMIN_PASSWORD}${NC}"
echo ""

